swagger: "2.0"
info:
  title: "MIS"
  description: "MIS Intimation"
  termsOfService: ""
  contact:
    name: "Test on Live 2021"
    email: "Test@test.com"
    x-mis-contact-email: 
      - "Test@test.com"
      - "Test@test.com"
    url: "http://"
  license:
    name: ""
    url: "http://"
  version: "1.0.0"
host: "www.Test.com"
basePath: "/api"
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /post_icici_transaction:
    post:
      tags: 
        - "eCollectionMIS"
      summary: Intimation.
      description: "MIS intimation."
      operationId: "Intimation"
      parameters:
        - description: "Intimation Notification."
          in: "body"
          name: "body"
          schema:
            $ref: "#/definitions/IntimationRequest"
      responses:
        '200':
          description: "Intimation Acknowledgment."
          schema:
            $ref: "#/definitions/IntimationResponse"
        400:
          description: "API request from sender application is not valid. One or more\
            \ mandatory fields were found missing from the request or were inconsistent."
          schema:
            $ref: "#/definitions/IntimationResponse"
        422:
          description: "API request from the sender application was understood but\
            \ declined as one or more mandatory business data fields were either missing\
            \ or had invalid data.'"
          schema:
            $ref: "#/definitions/IntimationResponse"
        500:
          description: "Server experienced an unexpected error that prevented\
            \ it from fulfilling the API request."
          schema:
            $ref: "#/definitions/IntimationResponse"
definitions:
  IntimationRequest:
    properties:
      client_code:
        type: "string"
        title: "Client Code"
        description: "Client Code - Virtual Code."
        minLength: 1
        maxLength: 6
        example: "3045"
      virtual_account_number:
        type: "string"
        title: "Virtual Account Number"
        description: "Unique actual virtual account no. of client."
        minLength: 4
        maxLength: 30
        example: "30450000000245376"
      transaction_amount:
        type: "string"
        title: "Transaction Amount"
        description: "Transaction Amount"
#       minLength: 4
        maxLength: 14
        pattern: "[0-9]{1,11}\\.[0-9]{2}"
        example: "10001.00"
      transaction_mode:
        type: "string"
        title: "Transaction Mode"
        description: "Payment Mode. NEFT: N, RTGS: R, FT: I, IMPS: O"
        minLength: 1
        maxLength: 1
        enum:
        - "N"
        - "R"
        - "I"
        - "O"
        example: "N"
      utr_number:
        type: "string"
        title: "UTR Number"
        description: "Unique Transaction Reference number generated by remitting bank."
#       minLength: 16
        maxLength: 30
        example: ""
      source_bank_holder_name:
        type: "string"
        title: "Remitter Name"
        description: "Remitter Name."
#       minLength: 0
        maxLength: 150
        example: ""
      source_bank_account_number:
        type: "string"
        title: "Remitter Account Number"
        description: "Account Number of the Remitter received from the Remitting Bank."
#       minLength: 0
        maxLength: 25
        example: ""
      source_bank_ifsc_code:
        type: "string"
        title: "Sender IFSC code"
        description: "IFSC code received from the Remitting Bank."
#       minLength: 0
        maxLength: 15
        example: ""
      transaction_date:
        type: "string"
        title: "Transaction Date"
        description: "DD-MM-YYYY (Date when the amount was received)."
        minLength: 10
        maxLength: 10
        pattern: "(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\\d\\d"
        example: "31-01-2020"
      sender_to_receiver_info:
        type: "string"
        title: "Sender to Receiver Information"
        description: "Sender to Receiver Information."
        minLength: 0
        maxLength: 150
        example: ""
    type: object 
    required:
    - client_code
    - virtual_account_number
    - transaction_amount
    - transaction_mode
    - utr_number
    - source_bank_holder_name
    - source_bank_account_number
    - source_bank_ifsc_code
    - transaction_date
  IntimationResponse:
    allOf:
    - $ref: "#/definitions/IntimationRequest"
    - type: "object"
      properties:
        Status:
          type: "string"
          title: "Status"
          description: "Decision point for collection. Recommended Values: ACCEPT / REJECT."
          enum:
          - "ACCEPT"
          - "REJECT"
          example: "ACCEPT"
        "Reject Reason":
          type: "string"
          title: "Reject Reason"
          description: "Reject reason is mandatory in case the Status received is REJECT else blank value. The funds will be remitted to the originating bank."
          minLength: 0
          maxLength: 35
          example: "Duplicate UTR number."
      required: 
      - Status